<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-ILEVVRC8" failures="5" tests="6" name="Test-edge" time="47.997" errors="0" timestamp="2025-07-10T16:34:42 IST">
  <testcase classname="BaseClass.BaseClass" name="@AfterMethod configAM" time="0.421">
    <failure type="org.openqa.selenium.ElementNotInteractableException" message="element not interactable: element has zero size
  (Session info: MicrosoftEdge=138.0.3351.77)
Build info: version: &amp;apos;4.27.0&amp;apos;, revision: &amp;apos;d6e718d134&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.11&amp;apos;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [5de1f4203bf409ce16bd35cc6fd73010, clickElement {id=f.E273C1CB41BE91C2D623007676CD794F.d.E00FA88D682A5E9FF9E4EBEDCF8103EE.e.1693}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 138.0.3351.77, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:59574}, msedge: {msedgedriverVersion: 138.0.3351.77 (efaf6935b436..., userDataDir: C:\Users\heman\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:59574/devtoo..., se:cdpVersion: 138.0.3351.77, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on windows (5de1f4203bf409ce16bd35cc6fd73010)] -&amp;gt; link text: Sign Out]
Session ID: 5de1f4203bf409ce16bd35cc6fd73010">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable: element has zero size
  (Session info: MicrosoftEdge=138.0.3351.77)
Build info: version: '4.27.0', revision: 'd6e718d134'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.11'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [5de1f4203bf409ce16bd35cc6fd73010, clickElement {id=f.E273C1CB41BE91C2D623007676CD794F.d.E00FA88D682A5E9FF9E4EBEDCF8103EE.e.1693}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 138.0.3351.77, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:59574}, msedge: {msedgedriverVersion: 138.0.3351.77 (efaf6935b436..., userDataDir: C:\Users\heman\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:59574/devtoo..., se:cdpVersion: 138.0.3351.77, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on windows (5de1f4203bf409ce16bd35cc6fd73010)] -> link text: Sign Out]
Session ID: 5de1f4203bf409ce16bd35cc6fd73010
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:76)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy18.click(Unknown Source)
at objectRepositoryUtility.HomePage.logoutOfApp(HomePage.java:98)
at BaseClass.BaseClass.configAM(BaseClass.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod configAM -->
  <testcase classname="BaseClass.BaseClass" name="@AfterClass configAC" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass configAC -->
  <testcase classname="CrmContactTest.CrmCreateContact" name="createContactWithOrg" time="4.648">
    <failure type="java.lang.AssertionError" message="expected [whatsapp4883] but found [[ ACC28188 ] whatsapp4883 - Organization Information]">
      <![CDATA[java.lang.AssertionError: expected [whatsapp4883] but found [[ ACC28188 ] whatsapp4883 - Organization Information]
at CrmContactTest.CrmCreateContact.createContactWithOrg(CrmCreateContact.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- createContactWithOrg -->
  <testcase classname="CrmContactTest.CrmCreateContact" name="createContactWithSupportDate" time="5.285">
    <failure type="java.lang.AssertionError" message="expected [2025-07-10] but found [   2025-07-10]">
      <![CDATA[java.lang.AssertionError: expected [2025-07-10] but found [   2025-07-10]
at CrmContactTest.CrmCreateContact.createContactWithSupportDate(CrmCreateContact.java:123)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- createContactWithSupportDate -->
  <testcase classname="CrmContactTest.CrmCreateContact" name="crmCreateContact" time="5.184">
    <failure type="java.lang.AssertionError" message="expected [gowda_628] but found [  gowda_628]">
      <![CDATA[java.lang.AssertionError: expected [gowda_628] but found [  gowda_628]
at CrmContactTest.CrmCreateContact.crmCreateContact(CrmCreateContact.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- crmCreateContact -->
  <testcase classname="CrmOrgTest.CreateOrg" name="CreateOrgWithIndustry" time="5.437">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at CrmOrgTest.CreateOrg.CreateOrgWithIndustry(CreateOrg.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- CreateOrgWithIndustry -->
  <testcase classname="CrmOrgTest.CreateOrg" name="CreateOrgWithPhNo" time="5.211"/>
  <testcase classname="CrmOrgTest.CreateOrg" name="createOrg" time="5.198">
    <failure type="java.lang.AssertionError" message="expected [[ ACC28195 ] insta_2627 - Organization Information] but found [insta_2627]">
      <![CDATA[java.lang.AssertionError: expected [[ ACC28195 ] insta_2627 - Organization Information] but found [insta_2627]
at CrmOrgTest.CreateOrg.createOrg(CreateOrg.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- createOrg -->
  <testcase classname="BaseClass.BaseClass" name="@AfterSuite configAs" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite configAs -->
  <testcase classname="BaseClass.BaseClass" name="@BeforeSuite configBS" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite configBS -->
</testsuite> <!-- Test-edge -->
